# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, unique=True)),
                ('description', models.CharField(default='', max_length=2048)),
                ('state', models.CharField(choices=[('S', 'Setup'), ('A', 'Active'), ('P', 'Paused'), ('F', 'Finished')], default='S', max_length=3)),
                ('weighted', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default=0, max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateField(null=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('L', 'Leader'), ('M', 'Member')], default='M', max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='votingmachine.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='list_of_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('category', models.CharField(choices=[('U', 'Useful'), ('A', 'Awesome'), ('C', 'Completion')], default='', max_length=1)),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='votingmachine.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'event', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('event', 'user')]),
        ),
    ]
