# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 00:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, unique=True)),
                ('description', models.CharField(default='', max_length=2048)),
                ('state', models.CharField(choices=[('S', 'Setup'), ('A', 'Active'), ('P', 'Paused'), ('F', 'Finished')], default='S', max_length=3)),
                ('weighted', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateField(null=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
