# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votingmachine', '0002_auto_20170523_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('leader', models.ForeignKey(default='Member', on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='votingmachine.Profile')),
                ('members', models.ManyToManyField(to='votingmachine.Profile', verbose_name='list of members')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
