# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 00:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votingmachine', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('category', models.CharField(choices=[('U', 'Useful'), ('A', 'Awesome'), ('C', 'Completion')], default='', max_length=1)),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='votingmachine.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingmachine.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='voting',
            unique_together=set([('user', 'event', 'category')]),
        ),
    ]
