# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingmachine', '0006_auto_20170621_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
