# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingmachine', '0007_auto_20170621_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_date',)},
        ),
    ]
