# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingmachine', '0008_auto_20170622_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('A', 'Active'), ('F', 'Finished')], default='A', max_length=10),
        ),
    ]
