# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170607_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(blank=True, max_length=255, unique=True, verbose_name='Email Address'),
        ),
    ]
