# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 16:00
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170622_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='states',
            field=django_fsm.FSMField(choices=[('N', 'New'), ('A', 'Approved')], default='N', max_length=50),
        ),
    ]
