# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_states'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='states',
            new_name='state',
        ),
    ]
