# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170802_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
